### ISSUE TITLE
TypeError: parentNode.body is not iterable in v11

### ISSUE THREAD

**Issue by jakebailey** [lydell/eslint-plugin-simple-import-sort#156]
I tried updating to v11 on the TypeScript repo, and got this:

```
Oops! Something went wrong! :(

ESLint: 8.56.0

TypeError: parentNode.body is not iterable
Occurred while linting /home/jabaile/work/TypeScript/src/harness/fourslashInterfaceImpl.ts:1
Rule: "simple-import-sort/imports"
    at Object.extractChunks (/home/jabaile/work/TypeScript/node_modules/eslint-plugin-simple-import-sort/shared.js:10:33)
    at Program:exit (/home/jabaile/work/TypeScript/node_modules/eslint-plugin-simple-import-sort/imports.js:67:38)
    at ruleErrorHandler (/home/jabaile/work/TypeScript/node_modules/eslint/lib/linter/linter.js:1076:28)
    at /home/jabaile/work/TypeScript/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/jabaile/work/TypeScript/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/jabaile/work/TypeScript/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/jabaile/work/TypeScript/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.leaveNode (/home/jabaile/work/TypeScript/node_modules/eslint/lib/linter/node-event-generator.js:349:14)
    at CodePathAnalyzer.leaveNode (/home/jabaile/work/TypeScript/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:824:23)
```

**Comment by jakebailey** [comment]
This is one of the few files with import declarations, so no doubt this was introduced in #149.

**Comment by MillerSvt** [comment]
@jakebailey please give some code to reproduce

**Comment by jakebailey** [comment]
The file is https://github.com/microsoft/TypeScript/blob/main/src/harness/fourslashInterfaceImpl.ts, but I'll try to minimize it.

**Comment by jakebailey** [comment]
This snippet does it:

```ts
export namespace Completion {
    export import CompletionSource = ts.Completions.CompletionSource;
}
```

**Comment by MillerSvt** [comment]
@jakebailey Thank you. Can you give your config for this rule?
Everything seems to be fine with the default configuration.
