### ISSUE TITLE
Plugin stops working if using eslint-plugin-vitest@0.5.4

### ISSUE THREAD

**Issue by Dannymx** [lydell/eslint-plugin-simple-import-sort#178]
I was updating some of my packages and I noticed my eslint auto fixes stopped working, after some debugging I narrowed it down to `"eslint-plugin-vitest": "^0.5.4"`, I'm not sure exactly was causing a conflict but reverting back to `"eslint-plugin-vitest": "^0.4.1"` fixes it.

Here's the log:
```
[Info  - 10:15:13 AM] ESLint server is starting.
[Info  - 10:15:13 AM] ESLint server running in node v20.14.0
[Info  - 10:15:13 AM] ESLint server is running.
[Info  - 10:15:15 AM] ESLint library loaded from: /Users/dsaldana/code/<redacted>/node_modules/eslint/lib/api.js
[Error - 10:15:21 AM] Calculating config file for file:///Users/dsaldana/code/<redacted>/src/components/pages/formula/formula-search.tsx) failed.
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'vitest' -> object with constructor 'Object'
    |     property 'configs' -> object with constructor 'Object'
    |     property 'recommended' -> object with constructor 'Object'
    --- property 'plugins' closes the circle
Referenced from: /Users/dsaldana/code/<redacted>/.eslintrc.json
    at JSON.stringify (<anonymous>)
    at /Users/dsaldana/code/<redacted>/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2156:45
    at Array.map (<anonymous>)
    at ConfigValidator.formatErrors (/Users/dsaldana/code/<redacted>/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2147:23)
    at ConfigValidator.validateConfigSchema (/Users/dsaldana/code/<redacted>/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2177:84)
    at ConfigArrayFactory._normalizeConfigData (/Users/dsaldana/code/<redacted>/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3019:19)
    at ConfigArrayFactory._loadExtendedPluginConfig (/Users/dsaldana/code/<redacted>/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3239:25)
    at ConfigArrayFactory._loadExtends (/Users/dsaldana/code/<redacted>/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3154:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/dsaldana/code/<redacted>/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)

```

I can provide more info about my other packages if necessary.

**Comment by lydell** [comment]
Hi!

I don’t have time to diagnose this. Can you make a minimal repo that reproduces the problem? The ESLint config must only use eslint-plugin-simple-import-sort and eslint-plugin-vitest and not extend any configs.

**Comment by Dannymx** [comment]
Marking this as closed, the issue is fixed by switching to `vitest/legacy-recommended` in my eslint config file, as mentioned [here](https://github.com/vitest-dev/eslint-plugin-vitest/issues/494).
